package models;

import java.lang.Long;
import java.util.*;

import javax.persistence.*;

import org.codehaus.jackson.JsonNode;

import play.Logger;
import play.db.ebean.*;
import play.data.format.*;
import play.data.validation.*;

import com.avaje.ebean.*;

import controllers.Utils;
import play.libs.F.*;
import play.libs.WS;


@Entity
@Table(name = "file", uniqueConstraints = { @UniqueConstraint(columnNames = {
		"owner", "path" }) })
public class File extends Model {

	enum Filetype {FILE, DIR};

	Long UUID;

	@Constraints.Required
	String path;
	@Constraints.Required
	String owner;
	@Constraints.Required
	Filetype type;
	long refID; // probably should be some other type

	public static Finder<Long,File> find = new Finder<Long,File>(Long.class, File.class); 

	public File(User user, String path, Filetype type) {
		//UUID = 1.0; // should be autogenerated by the system?
		this.owner = user.userName;
		this.path= path;
		this.type = type;
	}


}
