package models;

import java.lang.Long;
import java.util.*;

import javax.persistence.*;

import org.codehaus.jackson.JsonNode;

import play.Logger;
import play.db.ebean.*;
import play.data.format.*;
import play.data.validation.*;

import com.avaje.ebean.*;
import com.avaje.ebean.annotation.EnumValue;

import controllers.Utils;
import play.libs.F.*;
import play.libs.WS;


@Entity
@Table(name = "file", uniqueConstraints = { 
		@UniqueConstraint(columnNames = {"owner_id", "path" }) 
		})
public class File extends Model {

	public File() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 1766439519493690841L;

	enum Filetype {
		@EnumValue("F")
		FILE, 
		@EnumValue("D")
		DIR
		};

	/**Unique random 128bit long id generated by the DB*/
	@Id
	UUID uuid;

	@Column(nullable = false)
	@Constraints.Required
	String path;
	
	//I changed the type to User so it reflects the DB relations --Beshr
	@Column(name = "owner_id", nullable = false)
	@Constraints.Required
  @ManyToOne
  User owner;
	
	@Column(nullable = false)
	@Constraints.Required
	Filetype type;
	
//Long refID; // probably should be some other type
	//@Column(nullable = false)
	//@Constraints.Required
	@ManyToOne
	UserOwnedResource linkedResource;

	public static Finder<UUID,File> find = new Finder<UUID,File>(UUID.class, File.class); 

	public File(User user, String path, Filetype type) {
		//UUID = 1.0; // should be autogenerated by the system? //YES :)
		this.owner = user;
		this.path= path;
		this.type = type;
	}
	
	public void setLink(UserOwnedResource linkedResource) {
		this.linkedResource = linkedResource;
		if(uuid != null) {
			this.update();
		}
	}
	public UserOwnedResource getLink() {
		return linkedResource;
	}

}
